# fly.toml app configuration file generated for polished-moon-9390 on 2023-04-22T00:15:04-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "polished-moon-9390"
primary_region = "ord"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
